#First trial with German

#lxml parser must be installed 
import requests
import bs4
import pandas as pd


url = "https://wals.info/languoid/lect/wals_code_ger"
'''request_text = requests.get(url).content
#print(request_text) #it works

page = bs4.BeautifulSoup(request_text, "lxml")
print(page.find("title"))

print(page.find_all("table"))'''

#Problem: the data of the page is generated by Javascript after the page has been loaded

#i found the dataset downloaded by someone here: 
#https://www.kaggle.com/code/kerneler/starter-wals-dataset-ddb3fac7-a


